### ISSUE TITLE
Rambox Icon not applied after latest Rambox update

### ISSUE THREAD

**Issue by pakro** [bilelmoussaoui/Hardcode-Tray#659]
Hardcode-Tray: 4.3
Gtk: 3.24
Arch Linux

Problem with Rambox 0.7.6

### Expected behavior and actual behavior
The Rambox icon should be properly overwritten by the appropriate tray icon from hardcode-tray.

### Steps to reproduce the problem
1. sudo hardcode-tray --apply
2. restart Rambox

Output from command:

```
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: Inkscape
To Do: All
Applying now..


Rambox              [############........................] 1/3 33.3% 0.61s
Steam               [########################............] 2/3 66.7% 0.10s
Vivaldi             [####################################] 3/3 100.0% 0.22s
Took 0.93s to finish the tasks
```

**Comment by varlesh** [comment]
path added for `rambox`:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rambox
But not need fixed with `rambox-bin` or DEB:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rambox-bin

![image](https://user-images.githubusercontent.com/8083855/92240645-fc7d5500-eecd-11ea-8e4e-4e3ed3d5a7a2.png)

**Comment by pakro** [comment]
@varlesh Thx for the fix but unfortunately it still does not work for me. I'm using rambox-bin. I've tried everything but it won't show. But never mind, obviously I'm doing something wrong since you screenshot clearly shows it is working.

**Comment by varlesh** [comment]
try conversion tool RSVGConvert
`sudo -E hardcode-tray -ct RSVGConvert`

**Comment by pakro** [comment]
@varlesh Thanks for the hint! The conversion tool did indeed work. I create a configuration file for this so it always will use RSVGConvert.
